general:
  min-players: 2

messages:
  title:
    hunter:
      title: "&aYou're the hunter!"
      subtitle: "&7Hunt the runner."
    runner:
      title: "&cYou're the runner!"
      subtitle: "&7Run away from the hunters."

scoreboard:
  domain: 'www.amoojose.com'